// Action types
export const FETCH_DISCOVER = `FETCH_DISCOVER`;
export const FETCH_DISCOVER_SUCCESS = "FETCH_DISCOVER_SUCCESS";
export const FETCH_DISCOVER_ERROR = "FETCH_DISCOVER_ERROR";

// export const FETCH_TOP_MOVIES = `FETCH_TOP_MOVIES `;
// export const FETCH_DOCUMENTARIES = `FETCH_DOCUMENTARIES`;
